### ISSUE TITLE
Improve public information

### ISSUE THREAD

**Issue by dennisangemi** [danielediprima/appunti_fisica_2#2]
È possibile fare questi miglioramenti:

- [x] aggiungere descrizione repo 
![image](https://github.com/danielediprima/appunti_fisica_2/assets/77018886/cb751030-b054-4266-bedf-a9e2c503b5c0)

- [ ] nel README aggiungere riferimenti a author e contributor
- [x] nel README aggiungere istruzioni su segnalazioni errori

**Comment by danielediprima** [comment]
@dennisangemi author e contributor possono essere visti nei file
